---
fish_bin: /usr/bin/fish
fish_theme: bobthefish
fish_aliases:
  # https://opensource.com/article/19/7/bash-aliases
  - ls='ls -F'
  - ll='ls -lh'
  - mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
  - hg='history|grep'  # search bash history, I swapped the letters for github-cli compatibility
  - left='ls -t -1'  # most recently edited files
  - cg='cd `git rev-parse --show-toplevel`'  # go to git main level
fish_functions: []
fish_plugins: []
