---
# system arch -------------------------------------------------------------------
host_arch: 'amd64'

# browsers ----------------------------------------------------------------------
configure_chromium: true
configure_edge: true

# chats -------------------------------------------------------------------------
configure_slack: true
configure_telegram: true
configure_whatsdesk: true
configure_zoom: true

# desktop flavours --------------------------------------------------------------
configure_desktop: true
# if you set true to configure_desktop, you need to define the desktop_flavour
desktop_flavour: 'budgie'

# dev tools ---------------------------------------------------------------------
configure_codium: true
codium_preferences: |
  {
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Material Theme Palenight",
    "files.trimTrailingWhitespace": true
  }

configure_codium_extensions: true
codium_extensions:
  ## Ansible, Docker-Compose, etc.
  - redhat.vscode-yaml
  - redhat.vscode-xml

  ## General Development
  - oderwat.indent-rainbow

  ## PHP Development
  - bmewburn.vscode-intelephense-client
  - neilbrayfield.php-docblocker

  ## Vue.js Development
  - octref.vetur

  ## React Development
  - dsznajder.es7-react-js-snippets

  ## Code formatter
  - esbenp.prettier-vscode

  ## Markdown
  - shd101wyy.markdown-preview-enhanced

  ## Infrastructure
  - ms-azuretools.vscode-docker
  - hashicorp.terraform

  ## Themes
  - Equinusocio.vsc-material-theme
  - PKief.material-icon-theme

configure_projects: false
# projects:
#   - repo: git@github.com:1codehappy/laravel-api
#     dest: "~/Workspace/lpi"
#   - repo: git@github.com:1codehappy/laravel-workspace
#     dest: "~/Workspace/lws"
#   - repo: git@github.com:1giba/env
#     dest: "~/Workspace/env"

configure_git: true
# git_user: YourUser
# git_email: Your@Email
git_user: 1giba
git_email: olamundo@gmail.com

configure_postman: true

# infrastructure ------------------------------------------------------------------
configure_awscli: true
configure_docker: true
configure_kubectl: false # Unavailable at kubernetes repository for now.
configure_lens: false    # Can't install lens, depends on kubectl.
configure_ngrok: true

# miscelaneous -------------------------------------------------------------------
configure_flameshot: true
configure_morgen: true
configure_notion: true
configure_ulauncher: true

configure_wifi_powersave_mode: true
wifi_powersave_mode: '2'

# services -----------------------------------------------------------------------
configure_authy: true
configure_bitwarden: true
configure_spotify: true
configure_youtube_music: true

# shell -- -----------------------------------------------------------------------
configure_fish: true
configure_omf: true
configure_tilix: true

# installing and uninstalling ----------------------------------------------------
configure_apt_install: true
apt_install:
  - name: curl
  - name: htop
  - name: jq
  - name: meld
  - name: net-tools
  - name: silversearcher-ag
  - name: traceroute
  - name: vlc
  - name: vim
configure_apt_uninstall: true
apt_uninstall:
  - name: atril
  - name: aisleriot
  - name: celluloid
  - name: cheese
  - name: gnome-2048
  - name: gnome-mahjongg
  - name: gnome-mines
  - name: gnome-screenshot
  - name: gnome-sudoku
  - name: gnome-terminal
  - name: goodvibes
  - name: "libreoffice*"
  - name: lollypop
  - name: magnus
  - name: mate-calc
  - name: nautilus
  - name: parole
  - name: rhythmbox
