---
# used in URL of some deb packages on github
host_arch: "amd64"

# desktop flavours --------------------------------------------------------------
configure_desktop: false
# if you set true to configure_desktop, you need to declare the selected_desktop
# selected_desktop: 'budgie'
# selected_desktop: 'deepin' soon
# selected_desktop: 'kylin'

# dev tools ---------------------------------------------------------------------
configure_hyper: true # https://hyper.is

# you need to declare the git_user and git_email to handle with git
# create a config.yml file to define it.
# git_user: "John Doe"
# git_email: johndoe@example.com
configure_projects: false
# projects:
#   - repo: git@github.com:1codehappy/laravel-api
#     dest: "~/code/lpi"
#   - repo: git@github.com:1codehappy/laravel-workspace
#     dest: "~/code/lws"
#   - repo: git@github.com:1giba/env
#     dest: "~/code/env"


configure_codium: true # https://vscodium.com
configure_codium_extensions: true
codium_extensions:
  ## Ansible, Docker-Compose, etc.
  - redhat.vscode-yaml

  ## General Development
  - oderwat.indent-rainbow

  ## PHP Development
  - bmewburn.vscode-intelephense-client
  - neilbrayfield.php-docblocker

  ## Vue.js Development
  - octref.vetur

  ## React Development
  - dsznajder.es7-react-js-snippets

  ## Code formatter
  - esbenp.prettier-vscode

  ## Markdown
  - yzhang.markdown-all-in-one

  ## Infrastructure
  - ms-azuretools.vscode-docker
  - hashicorp.terraform

# docker --------------------------------------------------------------------------
configure_docker: true
docker_compose_version: v2.4.1

# infra tools ---------------------------------------------------------------------
configure_local_cluster: true # kind, kubectl, helm
configure_lens: true
configure_stacer: true
configure_terraform: true
configure_timeshift: true

# zsh ------------------------------------------------------------------------------
configure_zsh: true
zsh_theme: robbyrussell
zsh_custom_shell_command: "false"
# useful when users are bound to external systems (i.e. active directory)
# zsh_custom_shell_command: "true"
# zsh_default_shell_command: "/opt/pbis/bin/config LoginShellTemplate /usr/bin/zsh"
zsh_aliases:
  # https://opensource.com/article/19/7/bash-aliases
  # - ls='ls -F'
  # - ll='ls -lh'
  - mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
  - hg='history|grep'  # search bash history
  - left='ls -t -1'  # most recently edited files
  - cg='cd `git rev-parse --show-toplevel`'  # go to git main level
  - full-upgrade='sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y'
ohmyzsh_bundles:
  # Bundles from the default repo (robbyrussell's oh-my-zsh) only need a name
  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
  #
  # `name` is required (any valid file name will do so long as it's unique for the bundles)
  # `url` is git username/repo
  # `version` is git release and is required if `url` is define
  # - name: ansible
  # - name: aws
  # - name: docker
  # - name: docker-compose
  - name: gitfast
  # - name: pipenv
  # Syntax highlighting bundle.
  - name: 'zsh-syntax-highlighting'
    git:
      user: zsh-users
      repo: zsh-syntax-highlighting
      version: 0.7.1
  # # Autosuggestions
  # - name: zsh-autosuggestions # `name` is required (any valid file name will do so long as it's unique for the bundles)
  #   repo:
  #     user: zsh-users
  #     repo: zsh-autosuggestions
  #     version: v0.6.4

# Apps --------------------------------------------------------------
configure_snap_uninstall: true

configure_flatpak: true
flatpaks:
  - "org.chromium.Chromium" # Chromium
  - "org.chromium.Chromium.Codecs" # Codecs
  - "com.github.tchx84.Flatseal"  # Manage Flatpak permissions
  - "com.uploadedlobster.peek"  # Simple screen recorder with an easy to use interface
  - "com.github.junrrein.PDFSlicer"
  - "com.spotify.Client"  # Music
  - "com.slack.Slack" # Slack chat
  - "com.bitwarden.desktop"  # A secure and free password manager for all of your devices
  - "us.zoom.Zoom" # Video conference tool
  - "com.getpostman.Postman" # API development environment
  - "com.bitwarden.desktop" # Bitwarden desktop
  - "org.flameshot.Flameshot" # Print screen tool
  - "org.mozilla.firefox" # if you uninstall snap, you can add firefox

configure_apt_uninstall: false
# unused_packages:
#   - "libreoffice*"

# Miscelaneous ------------------------------------------------------
configure_ulauncher: true

configure_notion: true # https://notion.so
notion_version: v2.0.18-1 # https://github.com/notion-enhancer/notion-repackaged/releases

configure_wifi_powersave_mode: true
wifi_powersave_mode: '2'  # disable powersave
# https://twitter.com/dominucco/status/1410181146940411905?s=20
# According to https://gist.github.com/jcberthon/ea8cfe278998968ba7c5a95344bc8b55
# From the source code: wifi.powersave can have the following value:
#
#    NM_SETTING_WIRELESS_POWERSAVE_DEFAULT (0): use the default value
#    NM_SETTING_WIRELESS_POWERSAVE_IGNORE (1): don't touch existing setting
#    NM_SETTING_WIRELESS_POWERSAVE_DISABLE (2): disable powersave
#    NM_SETTING_WIRELESS_POWERSAVE_ENABLE (3): enable powersave

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through apt.
apt_packages:
  # Main
  - name: axel # https://github.com/axel-download-accelerator/axel
  - name: silversearcher-ag # https://github.com/ggreer/the_silver_searcher
  - name: vim
  # Audio Control
  - name: pulseaudio
  - name: pavucontrol

configure_airpods_pro_bluetooth_fix: false

# I have a XPS 13, so I needed to add the bug fix.
# https://www.dell.com/community/Linux-General/XPS-13-7390-Ubuntu-Screen-flickering/td-p/7430121
configure_screen_flickering_fix: false