---
- name: Hyper - Get latest release of a public repository
  community.general.github_release:
    user: vercel
    repo: hyper
    action: latest_release
  register: hyper_latest

- name: Hyper - Install deb from github (Latest)
  become: true
  apt:
    deb: >-
      https://github.com/vercel/hyper/releases/download/{{ hyper_latest.tag }}/hyper_{{ hyper_latest.tag|replace('v', '') }}_amd64.deb

- name: Hyper - Install plugins
  shell: hyper i {{ item }}
  loop: "{{ hyper_plugins }}"
