---
- name: PWA for Firefox - Install dependencies
  become: true
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: PWA for Firefox - Add GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://packagecloud.io/filips/FirefoxPWA/gpgkey
    state: present
    keyring: /usr/share/keyrings/firefoxpwa-keyring.gpg

- name: PWA for Firefox - Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/firefoxpwa-keyring.gpg] https://packagecloud.io/filips/FirefoxPWA/any any main
    state: present
    filename: firefoxpwa

- name: PWA for Firefox - Install package
  become: true
  apt:
    name: firefoxpwa
    state: present

- name: PWA for Firefox - Download and install Firefox browser runtime
  ansible.builtin.shell: firefoxpwa runtime install

- name: PWA for Firefox - Get all registered sites
  ansible.builtin.shell: firefoxpwa profile list
  register: firefoxpwa_profile_list

- name: PWA for Firefox - Check if the site is already installed
  set_fact:
    firefoxpwa_site: "{{ item }}"
  loop: "{{ pwa_manifests }}"
  when: item not in firefoxpwa_profile_list.stdout
  register: firefoxpwa_sites

- name: PWA for Firefox - Install site
  ansible.builtin.shell: firefoxpwa site install {{ firefoxpwa_site }} --profile 00000000000000000000000000
  when : firefoxpwa_site is defined
  loop: "{{ firefoxpwa_sites.results }}"

- name: PWA for Firefox - Change Whatsapp PWA icon
  include_tasks: whatsapp.yml
  when : pwa_whatsapp_manifest_url != ''
