---
- name: Snap - Remove store
  become: true
  snap:
    name: snap-store
    state: absent
  ignore_errors: yes

- name: Snap - Unmount
  become: true
  ansible.posix.mount:
    path: "/dev/loop*"
    state: absent

- name: Snap - Purge
  become: true
  apt:
    name: snapd
    state: absent
    purge: true
    allow_unauthenticated: yes
    allow_downgrade: yes

- name: Snap - Remove useless packages from the cache
  become: true
  apt:
    autoclean: yes

- name: Snap - Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Snap - Delete unused directory
  become: true
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - ~/snap/
    - /var/cache/snapd

- name: Snap - No snapd
  become: true
  copy:
    dest: /etc/apt/preferences.d/no_snapd
    content: |
      Package: snapd
      Pin: release a=*
      Pin-Priority: -10
