---
- name: Stacer - Get latest release of a public repository
  community.general.github_release:
    user: oguzhaninan
    repo: Stacer
    action: latest_release
  register: stacer_latest

- name: Stacer - Install deb from github (Latest Version)
  ansible.builtin.apt:
    deb: >-
      https://github.com/oguzhaninan/Stacer/releases/download/{{ stacer_latest.tag }}/stacer_{{ stacer_latest.tag | replace('v','') }}_{{ host_arch }}.deb
