---
- name: VSCodium - Collect code path location
  command:
    cmd: "which codium"
  changed_when: "false"
  register: code_installation_path

- name: VSCodium - Debug code path
  debug:
    var: code_installation_path.stdout

- name: VSCodium - Set code executable
  set_fact:
    code_executable: "{{ code_installation_path.stdout }}"

- name: VSCodium - Debug code path
  debug:
    var: code_executable

- name: VSCodium - Register currently installed code extensions
  shell: "{{ code_executable }} --list-extensions"
  register: installed_code_extensions
  changed_when: "false"

- name: VSCodium - Debug currently installed code extensions
  debug:
    var: installed_code_extensions.stdout_lines

- name: VSCodium - Install Code Extensions
  shell: "{{ code_executable }} --install-extension {{ item }}"
  with_items: "{{ codium_extensions }}"
  when: "item not in installed_code_extensions.stdout_lines"

- name: VSCodium - Debug Code Extensions Installed but not in variables
  debug:
    var: "{{ item }}"
  with_items: "{{ installed_code_extensions.stdout_lines }}"
  when: "item not in codium_extensions"
