---
- name: ULauncher - Get latest release of a public repository
  community.general.github_release:
    user: ulauncher
    repo: ulauncher
    action: latest_release
  register: ulauncher_latest

- name: ULauncher - Install deb from github (Latest)
  become: true
  apt:
    deb: >-
        https://github.com/Ulauncher/Ulauncher/releases/download/{{ulauncher_latest.tag}}/ulauncher_{{ ulauncher_latest.tag }}_all.deb
