---
- name: Helm - install apt package dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present

- name: Helm - Add apt key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Helm - Add repository
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm

- name: Helm - Install apt package
  apt:
    name: 'helm'
    state: latest
    update_cache: yes
