---
- name: Docker - install apt package dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Docker - Add Docker's official GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Docker - Install PPA
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker

- name: Docker - Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: "yes"

- name: Docker - Create the docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker - Add users to the group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: ["docker"]
    append: "yes"
  loop: "{{ docker_users|flatten(levels=1) }}"

- name: Compose - Get latest release of a public repository
  community.general.github_release:
    user: docker
    repo: compose
    action: latest_release
  register: docker_compose_version

- name: Docker - Check current docker-compose version.
  ansible.builtin.command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Docker - Delete existing docker-compose version if it's different.
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version.tag not in docker_compose_current_version.stdout

- name: Docker - Install Docker Compose (if configured).
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/\
          {{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "{{ docker_compose_path }}"
    mode: 0755
