---
- name: set fact ohmyzsh_plugins_folder
  set_fact:
      ohmyzsh_plugins_folder: ".oh-my-zsh/plugins"

- name: download zsh-plugins
  git:
      repo: "https://github.com/{{ item[0].user }}/{{ item[0].repo }}"
      dest: "~{{ item[1] }}/{{ ohmyzsh_plugins_folder }}/{{ item[0].repo }}"
      version: "{{ item[0].version }}"
  with_nested:
      # yamllint disable-line rule:line-length
      - "{{ ohmyzsh_bundles | map(attribute='git') | select('defined') | list }}"
      # yamllint disable-line rule:line-length
      - "{{ users | map(attribute='username') | select('defined') | list }}"
      # https://medium.com/opsops/filtering-away-an-undefined-value-from-a-list-in-ansible-867ff4574b60
  # If you care and can figure this out, I'll gladly review a PR :)
  changed_when: "false"
