---
- name: Timeshift - Install PPA
  ansible.builtin.apt_repository:
    repo: ppa:teejee2008/timeshift
    state: present

- name: Timeshift - Install apt package
  apt:
    name: "timeshift"
    state: present
    update_cache: "yes"
