---
galaxy_info:
  role_name: docker
  author: 1giba
  description: Ansible role to install docker and docker-compose

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: http://github.com/1giba/env/issues

  license: MIT

  min_ansible_version: 2.9

  #
  # Provide a list of supported platforms,
  # and for each platform a list of versions.
  # If you don't wish to enumerate all versions
  # for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags: ['system', 'development']
  # List tags for your role here, one per line.
  # A tag is a keyword that describes and categorizes the role.
  # Users find roles by searching for tags. Be sure to
  # remove the '[]' above, if you add tags to this list.
  # NOTE: A tag is limited to a single word comprised
  # of alphanumeric characters.
  #       Maximum 20 tags per role.

dependencies: []
# List your role dependencies here, one per line.
# Be sure to remove the '[]' above,
# if you add dependencies to this list.
